- hosts: all
  become: yes
  tasks: 
    - name: "Updating packages list"
      apt:
        update_cache: yes
    - name: "Copying the backup scrip to remote machine"
      copy: 
        src: /home/gautam/Desktop/zeeve/shell_scripts/02_backup.sh
        dest: /home/gautam
        mode: 0555
    - name: "Setting up cron job to run the script"
      cron:
        name: "Backup Script"
        job: "bash /home/gautam/02_backup.sh"
        minute: "0"
        hour: "0"
        day: "*/2"
        month: "*"
        weekday: "*"
    - name: "running the backup script"
      shell: bash /home/gautam/02_backup.sh
    - name: "Installing Nginx"
      apt:
        name: nginx
        state: present
    - name: "coping the static website to be served by nginx"
      copy:
        src: /mysites
        dest: /
    - name: "Configuring nginx.conf file to serve /mysites directory"
      template:
        src: ./nginx.conf.j2
        dest: /etc/nginx/nginx.conf
    - name: "reloading nginx configuration"
      shell: nginx -s reload
